name: Build Azure Virtual Network

on:
  workflow_dispatch:
    inputs:
      env_tag:
        default: "dev_1"
        description: "The environment name"
        required: true
  #push:
    #branches:
      #- dependabot/npm_and_yarn/ini-1.3.7

jobs:  
  Infra-vnet:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:  
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1.2.1
      - name: run terraform init
        run:  terraform init --backend-config="resource_group_name=32943" --backend-config="storage_account_name=cloudlegonewstorage" --backend-config="container_name=tfstate" --backend-config="key=${{ github.event.inputs.env_tag }}-state.tfstae"
        working-directory: vnet

      - name: run terraform plan
        run: terraform plan
        working-directory: vnet

      - name: run terraform apply
        run: terraform apply
        working-directory: vnet