name: Build Azure Virtual Network

on:
  workflow_dispatch:
    inputs:
      delete:
        description: "Delete and create the resources. Give yes or no"
        default: "no"
        required: false
      create:
        description: "Delete and create the resources. Give yes or no"
        default: "no"
        required: false
  #push:
    #branches:
      #- dependabot/npm_and_yarn/ini-1.3.7

jobs:  
  Infra-vnet:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:  
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1.2.1
      - name: run terraform init
        run:  terraform init
        working-directory: vnet

      - name: run terraform destroy
        if: ${{ github.event.inputs.delete == 'yes' }}
        run: terraform destroy --auto-approve
        working-directory: vnet

      - name: run terraform plan
        run: terraform plan
        working-directory: vnet

      - name: run terraform apply
        if: ${{ github.event.inputs.create == 'yes' }}
        run: terraform apply
        working-directory: vnet