name: Build Azure Virtual Network

on:
  workflow_dispatch:
    inputs:
      rgName:
        description: "resource group name"
        default: "32943"
        required: true
      location:
        description: "Azure location"
        default: "east us"
        required: true
  #push:
    #branches:
      #- dependabot/npm_and_yarn/ini-1.3.7

jobs:  
  Infra-vnet:
    runs-on: ubuntu-latest

    steps:  
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1.2.1
      #- name: login to Azure
        #run: az login --service-principal --username ${{ secrets.CLIENT_ID }} --password ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
      - name: run terraform init
        run:  |
          export ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}
          export ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}
          export ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}
          export ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}
          echo $ARM_CLIENT_ID
          terraform init
        working-directory:  vnet

      - name: run terraform plan
        run: terraform plan -var="location=${{ github.event.inputs.location }}" -var="rgName=${{ github.event.inputs.rgName }}" -var="client_id=${{ secrets.ARM_CLIENT_ID }}" -var="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}"
        working-directory:  vnet
      